bump jupiter-hw-support to align more with steamos

diff --git a/jupiter-hw-support/usr/bin/jupiter-check-support b/jupiter-hw-support/usr/bin/jupiter-check-support
--- a/jupiter-hw-support/usr/bin/jupiter-check-support
+++ b/jupiter-hw-support/usr/bin/jupiter-check-support
@@ -2,15 +2,24 @@
 
 set -e
 
-product_serial="$(cat /sys/devices/virtual/dmi/id/product_serial)"
-
-# Cutoff time for supported prototypes
-product_year="${product_serial:4:1}"
-product_week="${product_serial:5:2}"
-if [[ "$product_year" -eq "1" && "$product_week" -lt "33" ]]; then
-    echo "Supported: no"
-    exit 1
+if [ -x /usr/libexec/hwsupport/sysid ]; then
+  # If present, use script to clean up hardware with insignificant product name changes, such as the ROG Ally.
+  SYS_ID="$(/usr/libexec/hwsupport/sysid)"
+else
+  SYS_ID="$(cat /sys/devices/virtual/dmi/id/product_name)"
 fi
+if [[ ":Jupiter:Galileo:" =~ ":$SYS_ID:" ]]; then
 
-echo "Supported: yes"
-exit 0
+    product_serial="$(cat /sys/devices/virtual/dmi/id/product_serial)"
+
+    # Cutoff time for supported prototypes
+    product_year="${product_serial:4:1}"
+    product_week="${product_serial:5:2}"
+    if [[ "$product_year" -eq "1" && "$product_week" -lt "33" ]]; then
+        echo "Supported: no"
+        exit 1
+    fi
+
+    echo "Supported: yes"
+    exit 0
+fi
